[project]
name = "create-pytauri"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "pytauri == 0.5.*",
    "pydantic == 2.*",
    "anyio == 4.*",
    # [build-system]
    "setuptools>=61",
    "setuptools_scm>=8",
]
